-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 22:59:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`formato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formato` (
  `id_formato` INT NOT NULL AUTO_INCREMENT,
  `nombre_formato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_formato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion_estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consola` (
  `id_consola` INT NOT NULL AUTO_INCREMENT,
  `nombre_consola` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_consola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clasificacion` (
  `id_clasificacion` INT NOT NULL AUTO_INCREMENT,
  `caracteristicas_clasificacion` VARCHAR(45) NOT NULL,
  `edad_minima` INT NOT NULL,
  PRIMARY KEY (`id_clasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id_region` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_region`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videojuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videojuego` (
  `id_videojuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `precio_compra` INT NOT NULL,
  `precio_venta` INT NOT NULL,
  `fk_formato` INT NOT NULL,
  `fk_genero` INT NOT NULL,
  `fk_estado` INT NOT NULL,
  `fk_consola` INT NOT NULL,
  `fk_clasificacion` INT NOT NULL,
  `fk_region` INT NOT NULL,
  PRIMARY KEY (`id_videojuego`, `fk_formato`, `fk_genero`, `fk_estado`, `fk_consola`, `fk_clasificacion`, `fk_region`),
  INDEX `fk_videojuego_formato_idx` (`fk_formato` ASC) VISIBLE,
  INDEX `fk_videojuego_genero1_idx` (`fk_genero` ASC) VISIBLE,
  INDEX `fk_videojuego_estado1_idx` (`fk_estado` ASC) VISIBLE,
  INDEX `fk_videojuego_consola1_idx` (`fk_consola` ASC) VISIBLE,
  INDEX `fk_videojuego_clasificacion1_idx` (`fk_clasificacion` ASC) VISIBLE,
  INDEX `fk_videojuego_region1_idx` (`fk_region` ASC) VISIBLE,
  CONSTRAINT `fk_videojuego_formato`
    FOREIGN KEY (`fk_formato`)
    REFERENCES `mydb`.`formato` (`id_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_genero1`
    FOREIGN KEY (`fk_genero`)
    REFERENCES `mydb`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_estado1`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_consola1`
    FOREIGN KEY (`fk_consola`)
    REFERENCES `mydb`.`consola` (`id_consola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_clasificacion1`
    FOREIGN KEY (`fk_clasificacion`)
    REFERENCES `mydb`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_region1`
    FOREIGN KEY (`fk_region`)
    REFERENCES `mydb`.`region` (`id_region`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_region` (
  `id_estado` INT NOT NULL,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `entre_calle_2` VARCHAR(45) NOT NULL,
  `numero_interior` VARCHAR(45) NOT NULL,
  `numero_exterior` VARCHAR(45) NOT NULL,
  `fk_estado` INT NOT NULL,
  PRIMARY KEY (`id_direccion`, `fk_estado`),
  INDEX `fk_direccion_estado_region1_idx` (`fk_estado` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_estado_region1`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `mydb`.`estado_region` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccion_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion_usuario` (
  `direccion_id_direccion` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`direccion_id_direccion`, `usuario_id_usuario`),
  INDEX `fk_direccion_has_usuario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_direccion_has_usuario_direccion1_idx` (`direccion_id_direccion` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_has_usuario_direccion1`
    FOREIGN KEY (`direccion_id_direccion`)
    REFERENCES `mydb`.`direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `fk_videojuego` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  `precio_venta` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`fk_videojuego`, `fk_usuario`),
  INDEX `fk_videojuego_has_usuario_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_videojuego_has_usuario_videojuego1_idx` (`fk_videojuego` ASC) VISIBLE,
  CONSTRAINT `fk_videojuego_has_usuario_videojuego1`
    FOREIGN KEY (`fk_videojuego`)
    REFERENCES `mydb`.`videojuego` (`id_videojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videojuego_has_usuario_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id_ventas` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `total_venta` VARCHAR(45) NOT NULL,
  `fk_producto` INT NOT NULL,
  `fk_cliente` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `fk_producto`, `fk_cliente`),
  INDEX `fk_ventas_videojuego1_idx` (`fk_producto` ASC) VISIBLE,
  INDEX `fk_ventas_usuario1_idx` (`fk_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_videojuego1`
    FOREIGN KEY (`fk_producto`)
    REFERENCES `mydb`.`videojuego` (`id_videojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuario1`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `id_detalle_venta` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `id_ventas` INT NOT NULL,
  PRIMARY KEY (`id_detalle_venta`, `id_ventas`),
  INDEX `fk_detalle_venta_ventas1_idx` (`id_ventas` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_ventas1`
    FOREIGN KEY (`id_ventas`)
    REFERENCES `mydb`.`ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_pago` (
  `id_estado_pago` INT NOT NULL,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pago` (
  `id_tipo_pago` INT NOT NULL,
  `detalle_tipo_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `id_pago` INT NOT NULL,
  `tipo_pago` VARCHAR(45) NULL,
  `cantidad_pagada` VARCHAR(45) NULL,
  `fecha_hora_pago` VARCHAR(45) NULL,
  `fk_usuario` INT NOT NULL,
  `fk_venta` INT NOT NULL,
  `fk_estado_pago` INT NOT NULL,
  `fk_tipo_pago` INT NOT NULL,
  PRIMARY KEY (`id_pago`, `fk_usuario`, `fk_venta`, `fk_estado_pago`, `fk_tipo_pago`),
  INDEX `fk_pago_usuario1_idx` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_pago_ventas1_idx` (`fk_venta` ASC) VISIBLE,
  INDEX `fk_pago_estado_pago1_idx` (`fk_estado_pago` ASC) VISIBLE,
  INDEX `fk_pago_tipo_pago1_idx` (`fk_tipo_pago` ASC) VISIBLE,
  CONSTRAINT `fk_pago_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_ventas1`
    FOREIGN KEY (`fk_venta`)
    REFERENCES `mydb`.`ventas` (`id_ventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_estado_pago1`
    FOREIGN KEY (`fk_estado_pago`)
    REFERENCES `mydb`.`estado_pago` (`id_estado_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_tipo_pago1`
    FOREIGN KEY (`fk_tipo_pago`)
    REFERENCES `mydb`.`tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
